$(function(){
  $("#XMLID_1_").click(function(){
    console.log('eneomr')
    console.log($('#email').val())
  });
  $("#XMLID_2_").click(function(){
    console.log("plop1");
  });
  $("#XMLID_3_").click(function(){
    console.log("etage4");
  });
  $("#XMLID_4_").click(function(){
    console.log("etage3");
  });
});